/**
 * Shared constants and regexes for syntax highlighting and HTML normalization.
 */

/**
 * Shared syntax metadata used by lightweight tokenizers in `shared/syntax`.
 *
 * The exports below are grouped by responsibility:
 * - language aliases and regex helpers
 * - keyword sets
 * - primitive type sets
 * - symbol and operator sets
 * - language-to-set lookup maps
 */
export const LANGUAGE_ALIASES: Record<string, string> = {
  c: 'cpp',
  'c++': 'cpp',
  cc: 'cpp',
  css: 'scss',
  cplusplus: 'cpp',
  cxx: 'cpp',
  htm: 'html',
  mdown: 'markdown',
  js: 'javascript',
  jsx: 'javascript',
  md: 'markdown',
  py: 'python',
  sass: 'scss',
  scss: 'scss',
  sh: 'bash',
  shell: 'bash',
  terminal: 'bash',
  ts: 'typescript',
  tsx: 'typescript',
  zsh: 'bash',
};

export const PRE_BLOCK_REGEX = /<pre\b([^>]*)>([\s\S]*?)<\/pre>/gi;
export const CODE_BLOCK_REGEX = /<code\b([^>]*)>([\s\S]*?)<\/code>/gi;
export const CODE_TAG_REGEX = /<code\b([^>]*)>([\s\S]*?)<\/code>/i;
export const CODE_TAG_REPLACE_REGEX = /<code\b[^>]*>[\s\S]*?<\/code>/i;

/** Keyword sets used by language-specific tokenizers. */
export const SCRIPT_KEYWORDS = new Set([
  'as',
  'async',
  'await',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'else',
  'enum',
  'export',
  'extends',
  'finally',
  'for',
  'from',
  'function',
  'if',
  'implements',
  'import',
  'in',
  'instanceof',
  'interface',
  'let',
  'namespace',
  'new',
  'package',
  'private',
  'protected',
  'public',
  'readonly',
  'return',
  'static',
  'super',
  'switch',
  'this',
  'throw',
  'try',
  'type',
  'typeof',
  'var',
  'void',
  'while',
  'with',
  'yield',
]);

export const CPP_KEYWORDS = new Set([
  'auto',
  'bool',
  'break',
  'case',
  'catch',
  'char',
  'class',
  'const',
  'constexpr',
  'continue',
  'default',
  'delete',
  'do',
  'double',
  'else',
  'enum',
  'extern',
  'false',
  'float',
  'for',
  'friend',
  'if',
  'inline',
  'int',
  'long',
  'namespace',
  'new',
  'nullptr',
  'operator',
  'private',
  'protected',
  'public',
  'return',
  'short',
  'signed',
  'sizeof',
  'static',
  'struct',
  'switch',
  'template',
  'this',
  'throw',
  'true',
  'try',
  'typedef',
  'typename',
  'union',
  'unsigned',
  'using',
  'virtual',
  'void',
  'while',
]);

export const HTML_KEYWORDS = new Set([
  'a',
  'article',
  'aside',
  'audio',
  'body',
  'button',
  'canvas',
  'code',
  'div',
  'doctype',
  'em',
  'footer',
  'form',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'head',
  'header',
  'html',
  'iframe',
  'img',
  'input',
  'label',
  'li',
  'link',
  'main',
  'meta',
  'nav',
  'ol',
  'option',
  'p',
  'script',
  'section',
  'select',
  'small',
  'span',
  'strong',
  'style',
  'table',
  'tbody',
  'td',
  'textarea',
  'th',
  'thead',
  'title',
  'tr',
  'ul',
  'video',
]);

export const SCSS_KEYWORDS = new Set([
  '@at-root',
  '@content',
  '@debug',
  '@each',
  '@else',
  '@error',
  '@extend',
  '@for',
  '@forward',
  '@function',
  '@if',
  '@import',
  '@include',
  '@media',
  '@mixin',
  '@return',
  '@use',
  '@warn',
  '@while',
  'and',
  'calc',
  'clamp',
  'darken',
  'hsl',
  'hsla',
  'lighten',
  'linear-gradient',
  'map-get',
  'max',
  'min',
  'not',
  'nth',
  'or',
  'percentage',
  'radial-gradient',
  'rgb',
  'rgba',
  'saturate',
  'transparentize',
]);

export const TERMINAL_KEYWORDS = new Set([
  'alias',
  'awk',
  'bash',
  'break',
  'case',
  'cat',
  'cd',
  'chmod',
  'chown',
  'clear',
  'continue',
  'cp',
  'curl',
  'cut',
  'date',
  'declare',
  'df',
  'diff',
  'do',
  'done',
  'echo',
  'elif',
  'else',
  'env',
  'esac',
  'eval',
  'exec',
  'exit',
  'export',
  'false',
  'fi',
  'find',
  'for',
  'function',
  'git',
  'grep',
  'head',
  'history',
  'if',
  'in',
  'jobs',
  'kill',
  'less',
  'ln',
  'ls',
  'make',
  'man',
  'mkdir',
  'mv',
  'nano',
  'printf',
  'ps',
  'pwd',
  'read',
  'return',
  'rm',
  'rmdir',
  'sed',
  'set',
  'shift',
  'sort',
  'source',
  'sudo',
  'tail',
  'tar',
  'then',
  'touch',
  'trap',
  'true',
  'type',
  'uname',
  'unset',
  'until',
  'wait',
  'wc',
  'while',
  'which',
  'xargs',
  'zsh',
]);

export const PYTHON_KEYWORDS = new Set([
  'and',
  'as',
  'assert',
  'async',
  'await',
  'break',
  'case',
  'class',
  'continue',
  'def',
  'del',
  'elif',
  'else',
  'except',
  'False',
  'finally',
  'for',
  'from',
  'global',
  'if',
  'import',
  'in',
  'is',
  'lambda',
  'match',
  'None',
  'nonlocal',
  'not',
  'or',
  'pass',
  'raise',
  'return',
  'True',
  'try',
  'while',
  'with',
  'yield',
]);

export const MARKDOWN_KEYWORDS = new Set([
  'blockquote',
  'code',
  'emphasis',
  'fence',
  'footnote',
  'heading',
  'hr',
  'image',
  'inline',
  'link',
  'list',
  'ol',
  'quote',
  'strikethrough',
  'strong',
  'table',
  'task',
  'ul',
]);

/** Canonical language-id sets used by fixed-language tokenizers. */
export const CPP_LANGUAGES = new Set(['cpp'] as const);
export const MARKDOWN_LANGUAGES = new Set(['markdown'] as const);
export const PYTHON_LANGUAGES = new Set(['python'] as const);
export const STYLE_LANGUAGES = new Set(['scss'] as const);
export const TERMINAL_LANGUAGES = new Set(['bash'] as const);

/** Primitive type sets used when tokenizing language literals and built-ins. */
export const COMMON_PRIMITIVE_TYPES = new Set(['string', 'number', 'boolean', 'null', 'undefined']);

export const SCRIPT_PRIMITIVE_TYPES = new Set([
  ...COMMON_PRIMITIVE_TYPES,
  'any',
  'bigint',
  'never',
  'object',
  'symbol',
  'unknown',
  'void',
]);

export const HTML_PRIMITIVE_TYPES = new Set<string>();

export const SCSS_PRIMITIVE_TYPES = new Set(['number', 'string', 'bool', 'null', 'color', 'list', 'map']);

export const TERMINAL_PRIMITIVE_TYPES = new Set(['string', 'number', 'boolean', 'array', 'null']);

export const PYTHON_PRIMITIVE_TYPES = new Set(['int', 'float', 'bool', 'str', 'bytes', 'NoneType']);

export const MARKDOWN_PRIMITIVE_TYPES = new Set<string>();

export const CPP_PRIMITIVE_TYPES = new Set([
  'bool',
  'char',
  'double',
  'float',
  'int',
  'long',
  'short',
  'signed',
  'unsigned',
  'void',
]);

/** Symbol and operator sets used by languages with punctuation-aware tokenizers. */
export const COMMON_SYMBOLS = new Set(['(', ')', '{', '}', '[', ']', ',', '.', ':', ';', '"', "'"]);

export const COMMON_OPERATORS = new Set(['=', '==', '!=', '>', '<', '>=', '<=', '+', '-', '*', '/', '%']);

export const SCRIPT_SYMBOLS = new Set([...COMMON_SYMBOLS, '?', '`']);

export const CPP_SYMBOLS = new Set([...COMMON_SYMBOLS, '<', '>']);

export const SCRIPT_OPERATORS = new Set([
  ...COMMON_OPERATORS,
  '===',
  '!==',
  '&&',
  '||',
  '!',
  '??',
  '?.',
  '=>',
  '++',
  '--',
  '+=',
  '-=',
  '*=',
  '/=',
  '%=',
  '&',
  '|',
  '^',
  '~',
  '<<',
  '>>',
  '>>>',
  '&=',
  '|=',
  '^=',
  '<<=',
  '>>=',
  '>>>=',
  '**',
  '**=',
]);

export const CPP_OPERATORS = new Set([
  ...COMMON_OPERATORS,
  '&&',
  '||',
  '!',
  '++',
  '--',
  '+=',
  '-=',
  '*=',
  '/=',
  '%=',
  '&',
  '|',
  '^',
  '~',
  '<<',
  '>>',
  '&=',
  '|=',
  '^=',
  '<<=',
  '>>=',
  '::',
  '->',
]);

export const HTML_SYMBOLS = new Set([...COMMON_SYMBOLS, '<', '>', '</', '/>', '<!--', '-->']);

export const HTML_OPERATORS = new Set([...COMMON_OPERATORS]);

export const SCSS_SYMBOLS = new Set([...COMMON_SYMBOLS, '$', '@', '&', '#', '#{', '}']);

export const SCSS_OPERATORS = new Set([...COMMON_OPERATORS, 'and', 'or', 'not', '==', '!=', '>', '<', '>=', '<=', '/']);

export const TERMINAL_SYMBOLS = new Set([...COMMON_SYMBOLS, '$', '~', '/', './', '../', '*', '?', '!']);

export const TERMINAL_OPERATORS = new Set([
  ...COMMON_OPERATORS,
  '|',
  '||',
  '&&',
  ';',
  ';;',
  '&',
  '>',
  '>>',
  '<',
  '<<',
  '2>',
  '2>>',
  '&>',
  '|&',
]);

export const PYTHON_SYMBOLS = new Set([...COMMON_SYMBOLS, '@']);

export const PYTHON_OPERATORS = new Set([
  ...COMMON_OPERATORS,
  '//',
  '**',
  ':=',
  'and',
  'or',
  'not',
  'is',
  'in',
  '+=',
  '-=',
  '*=',
  '/=',
  '//=',
  '%=',
  '**=',
  '&',
  '|',
  '^',
  '~',
  '<<',
  '>>',
  '&=',
  '|=',
  '^=',
  '<<=',
  '>>=',
]);

export const MARKDOWN_SYMBOLS = new Set([
  ...COMMON_SYMBOLS,
  '#',
  '##',
  '###',
  '####',
  '#####',
  '######',
  '-',
  '*',
  '+',
  '>',
  '`',
  '```',
  '|',
  '![',
  '[',
  ']',
  '(',
  ')',
  '~~',
]);

export const MARKDOWN_OPERATORS = new Set([...COMMON_OPERATORS, '---', '***', '___']);

/** Lookup maps keyed by normalized language identifiers. */
export const LANGUAGE_SYMBOLS: Record<string, ReadonlySet<string>> = {
  javascript: SCRIPT_SYMBOLS,
  typescript: SCRIPT_SYMBOLS,
  cpp: CPP_SYMBOLS,
  html: HTML_SYMBOLS,
  scss: SCSS_SYMBOLS,
  bash: TERMINAL_SYMBOLS,
  shell: TERMINAL_SYMBOLS,
  terminal: TERMINAL_SYMBOLS,
  python: PYTHON_SYMBOLS,
  markdown: MARKDOWN_SYMBOLS,
};

export const LANGUAGE_OPERATORS: Record<string, ReadonlySet<string>> = {
  javascript: SCRIPT_OPERATORS,
  typescript: SCRIPT_OPERATORS,
  cpp: CPP_OPERATORS,
  html: HTML_OPERATORS,
  scss: SCSS_OPERATORS,
  bash: TERMINAL_OPERATORS,
  shell: TERMINAL_OPERATORS,
  terminal: TERMINAL_OPERATORS,
  python: PYTHON_OPERATORS,
  markdown: MARKDOWN_OPERATORS,
};

export const LANGUAGE_PRIMITIVE_TYPES: Record<string, ReadonlySet<string>> = {
  javascript: SCRIPT_PRIMITIVE_TYPES,
  typescript: SCRIPT_PRIMITIVE_TYPES,
  cpp: CPP_PRIMITIVE_TYPES,
  html: HTML_PRIMITIVE_TYPES,
  scss: SCSS_PRIMITIVE_TYPES,
  bash: TERMINAL_PRIMITIVE_TYPES,
  shell: TERMINAL_PRIMITIVE_TYPES,
  terminal: TERMINAL_PRIMITIVE_TYPES,
  python: PYTHON_PRIMITIVE_TYPES,
  markdown: MARKDOWN_PRIMITIVE_TYPES,
};
