/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeBadge: typeof import('primevue/badge')['default']
    PrimeButton: typeof import('primevue/button')['default']
    PrimeCard: typeof import('primevue/card')['default']
    PrimeCheckbox: typeof import('primevue/checkbox')['default']
    PrimeChip: typeof import('primevue/chip')['default']
    PrimeDialog: typeof import('primevue/dialog')['default']
    PrimeDivider: typeof import('primevue/divider')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeMessage: typeof import('primevue/message')['default']
    PrimePanel: typeof import('primevue/panel')['default']
    PrimePassword: typeof import('primevue/password')['default']
    PrimeProgressBar: typeof import('primevue/progressbar')['default']
    PrimeSelect: typeof import('primevue/select')['default']
    PrimeTab: typeof import('primevue/tab')['default']
    PrimeTabList: typeof import('primevue/tablist')['default']
    PrimeTabPanel: typeof import('primevue/tabpanel')['default']
    PrimeTabPanels: typeof import('primevue/tabpanels')['default']
    PrimeTabs: typeof import('primevue/tabs')['default']
    PrimeTag: typeof import('primevue/tag')['default']
    PrimeTextarea: typeof import('primevue/textarea')['default']
    PrimeTimeline: typeof import('primevue/timeline')['default']
    PrimeToast: typeof import('primevue/toast')['default']
    PrimeToggleSwitch: typeof import('primevue/toggleswitch')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
